Maquinaria/urls.py
from django.urls import path
from Maquinaria import views
app_name = 'maquinaria'


urlpatterns = [
    path('home', views.Home, name='home'),
    path('maquina', views.MaquinaListView.as_view(), name='maquina-list'),
    path('maquina/create', views.MaquinaCreateView.as_view(), name='maquina-create'),
    path('maquina/buscar', views.searchMaquina, name='maquina-search'),
    path('maquina/<int:pk>', views.MaquinaDetailView.as_view(), name='maquina-detail'),   
    path('maquina/<int:pk>/update', views.MaquinaUpdateView.as_view(), name='maquina-update'), 
    path('maquina/<int:id>/delete', views.MaquinaDeleteView, name='maquina-delete'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', include('Maquinaria.urls')),
]

Maquinaria/models.py
from django.db import models

class Maquina(models.Model):
    ESTADO = (
        ('BL', 'BLOQUEADA'),
        ('MA', 'MANTENCION'),
        ('DI', 'DISPONIBLE'),
        ('AR', 'ARRENDADA'),
    )

    Modelos = (
        ('903', '903D'),
        ('906', '906M'),
        ('AG', 'Ag Handler 906M'),
        ('AH', 'Ag Handler 907M'),
    )

    modelo = models.CharField(max_length=50, choices=Modelos)
    patente = models.CharField(max_length=150, unique=True)
    agno = models.PositiveSmallIntegerField()
    estado = models.CharField(max_length=50, choices=ESTADO, default='DI')


    def __str__(self):
        return self.modelo
    
    def estado_verbose(self):
        return dict(Maquina.ESTADO)[self.estado]

    def modelo_verbose(self):
        return dict(Maquina.Modelos)[self.modelo]

#bloqueada - mantencion - disponible - arrendada

Maquinaria/forms.py
from django import forms

class MaquinaForm(forms.Form):
    patente =  forms.CharField(label='Patente', help_text="Patente con el siguiente formato XX-XX-11")

Maquinaria/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from Maquinaria.models import Maquina
from Maquinaria.forms import MaquinaForm
from django.db import IntegrityError

@method_decorator(login_required, name='dispatch')
class MaquinaListView(ListView):
    model = Maquina
    template_name = 'listado_maquina.html'
    context_object_name = 'maquinas'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(MaquinaListView, self).get_context_data(**kwargs)
        maquinas = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(maquinas, self.paginate_by)
        try:
            maquinas = paginator.page(page)
        except PageNotAnInteger:
            maquinas = paginator.page(1)
        except EmptyPage:
            maquinas = paginator.page(paginator.num_pages)
        context['maquinas'] = maquinas
        return context

@method_decorator(login_required, name='dispatch')
class MaquinaCreateView(CreateView):
    model = Maquina
    template_name = 'create.html'
    fields = ('modelo', 'agno', 'patente', 'estado')
    success_url = reverse_lazy('maquinaria:maquina-list')

@method_decorator(login_required, name='dispatch')
class MaquinaDetailView(DetailView):
    model = Maquina
    template_name = 'detail.html'
    context_object_name = 'maquina'

@method_decorator(login_required, name='dispatch')
class MaquinaUpdateView(UpdateView):

    model = Maquina
    template_name = 'update.html'
    context_object_name = 'maquina'
    fields = ('modelo', 'agno', 'patente', 'estado')

    def get_success_url(self):
        return reverse_lazy('maquinaria:maquina-detail', kwargs={'pk': self.object.id})

def MaquinaDeleteView(request, id):
    data = {}
    template_name = 'delete.html'
    data['maquina'] = Maquina.objects.get(pk=id)
    if request.method == 'POST':
        data['maquina'].estado = 'BL'
        data['maquina'].save()
        return redirect('maquinaria:maquina-list')
    
    return render (request, template_name, data)

def searchMaquina(request):
    data = {}
    template_name = 'patente-consulta.html'
    data['form'] = MaquinaForm(request.POST or None)

    if request.method == 'POST':
        if data['form'].is_valid():
            try:
                pat = request.POST['patente']
                maquina = Maquina.objects.get(patente=pat)
                
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Consulta realizada con exito'
                )
                return redirect('maquinaria:maquina-detail', pk=maquina.id)
            except ObjectDoesNotExist:
                maquina = None
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Rut no registra multas',
                )

            except IntegrityError as ie:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Problemas al realizar la consulta: {error}.'.format(
                        error=str(ie))
                )
            
        else:
            messages.add_message(
                request,
                messages.ERROR,
                'Problemas al realizar la consulta',
            )
        
    return render(request, template_name, data)


def Home(request):
    data = {}
    template_name = 'home.html'

    return render(request, template_name, data)

Maquinaria/templates/_pagination.html
<nav aria-label="navigation">
    <ul class="pagination justify-content-end mb-0">
{% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <i class="fas fa-angle-left"></i>
            <span class="sr-only">Previous</span>
        </a>
    </li>
{% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">
            <i class="fas fa-angle-left"></i>
            <span class="sr-only">Previous</span>
        </a>
    </li>
{% endif %}

{% for i in page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item active">
        <a class="page-link" href="?page={{ i }}">{{ page_obj.number }}</a>
      </li>
    {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
    <li class="page-item">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
    {% endif %}
{% endfor %}

{% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
    <li><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
{% endif %}

{% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          <i class="fas fa-angle-right"></i>
          <span class="sr-only">Next</span>
        </a>
      </li>
{% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">
            <i class="fas fa-angle-right"></i>
            <span class="sr-only">Next</span>
        </a>
    </li>
{% endif %}
</ul>
</nav>

Maquinaria/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% block meta_tags %}{% endblock %}
  <title>{% block title %}Maquinas{% endblock %}</title>
  <script src="https://kit.fontawesome.com/686111fdd6.js" crossorigin="anonymous"></script> 

  {% block css %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  {% endblock %}

  {% block custom_css %}
  {% endblock %}
</head>
<body>

  {% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'maquinaria:home' %}">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'maquinaria:maquina-list' %}">Maquinas</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% endblock %}

  <div class="container mt-4">
  {% block container %}
  {% endblock %}
  </div>

  {% block js %}
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  {% endblock %}

  {% block custom_js %}
  {% endblock %}
</body>
</html>

Maquinaria/templates/create.html
{% extends "base.html" %}

{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Create a New Machine</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Create</button>
        </form>
    </div>
</div>
{% endblock %}

Maquinaria/templates/delete.html
{% extends "base.html" %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Dar de baja maquina #{{maquina.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Esta seguro de dar de baja la maquina<strong>{{ maquina }}</strong> ?
            </div>
            <a href="{% url 'maquinaria:maquina-list' %}"><button type="button" class="btn btn-primary">Volver atrás</button></a>
            <button type="submit" class="btn btn-danger">Dar de baja</button>
        </form>
    </div>
</div>
{% endblock %}

Maquinaria/templates/detail.html
{% extends "base.html" %}
{% block container %}

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Maquina Details #{{maquina.id}}</h5>
    </div>
    <div class="card-body">
    <dl class="row">
      <dt class="col-sm-3">Maquina Modelo</dt>
      <dd class="col-sm-9">{{ maquina.modelo_verbose }}</dd>
      <dt class="col-sm-3">Año</dt>
      <dd class="col-sm-9">{{ maquina.agno }}</dd>
      <dt class="col-sm-3">Patente</dt>
      <dd class="col-sm-9">{{ maquina.patente }}</dd>
      <dt class="col-sm-3">Estado</dt>
      <dd class="col-sm-9">{{ maquina.estado_verbose }}</dd>
    </dl>

    </div>
</div>

{% endblock %}

Maquinaria/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block partials %}

{% endblock %}

{% block container %}
<h1 style="text-align: center;">Modulos</h1>

<div class="row">
    <div class="col-sm-4 mt-3">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Personas <strong>(en desarrollo)</strong></h5>
              <h6 class="card-subtitle mb-2 text-muted">Mantenedor personas</h6>
              <p class="card-text">Aquí podrás revisar toda persona registrada en el sistema</p>
              <a href="#" class="card-link"><i class="far fa-plus-square" style="font-size: large;"></i></a>
              <a href="#" class="card-link"><i class="fas fa-list" style="font-size: large;"></i></a>
            </div>
          </div>
    </div>
    <div class="col-sm-4 mt-3">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Maquinas</h5>
              <h6 class="card-subtitle mb-2 text-muted">Mantenedor Maquinas</h6>
              <p class="card-text">Aquí podrás revisar toda maquina registrada en el sistema</p>
              <a href="{% url 'maquinaria:maquina-create' %}" class="card-link"><i class="far fa-plus-square" style="font-size: large;"></i></a>
              <a href="{% url 'maquinaria:maquina-list' %}" class="card-link"><i class="fas fa-list" style="font-size: large;"></i></a>
              <a href="{% url 'maquinaria:maquina-search' %}" class="card-link"><i class="fas fa-search" style="font-size: large;"></i></a>
            </div>
          </div>
    </div>
    <div class="col-sm-4 mt-3">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Clientes <strong>(en desarrollo)</strong></h5>
              <h6 class="card-subtitle mb-2 text-muted">Mantenedor clientes</h6>
              <p class="card-text">Aquí podrás revisar todo cliente registrado en el sistema</p>
              <a href="#" class="card-link"><i class="far fa-plus-square" style="font-size: large;"></i></a>
              <a href="#" class="card-link"><i class="fas fa-list" style="font-size: large;"></i></a>
            </div>
          </div>
    </div>
    <div class="col-sm-4 mt-3">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Registro de arriendos <strong>(en desarrollo)</strong></h5>
              <h6 class="card-subtitle mb-2 text-muted">Mantenedor arriends</h6>
              <p class="card-text">Aquí podrás revisar todo arriendo registrado en el sistema</p>
              <a href="#" class="card-link"><i class="far fa-plus-square" style="font-size: large;"></i></a>
              <a href="#" class="card-link"><i class="fas fa-list" style="font-size: large;"></i></a>
            </div>
          </div>
    </div>
    <div class="col-sm-4 mt-3">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Dispositivos moviles <strong>(en desarrollo)</strong></h5>
              <h6 class="card-subtitle mb-2 text-muted">Mantenedor Dispositivos moviles</h6>
              <p class="card-text">Aquí podrás revisar todo movil registrado en el sistema</p>
              <a href="#" class="card-link"><i class="far fa-plus-square" style="font-size: large;"></i></a>
              <a href="#" class="card-link"><i class="fas fa-list" style="font-size: large;"></i></a>
            </div>
          </div>
    </div>
    <div class="col-sm-4 mt-3">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Trabajadores <strong>(en desarrollo)</strong></h5>
              <h6 class="card-subtitle mb-2 text-muted">Mantenedor inspector</h6>
              <p class="card-text">Aquí podrás revisar todo inspector registrado en el sistema</p>
              <a href="#" class="card-link"><i class="far fa-plus-square" style="font-size: large;"></i></a>
              <a href="#" class="card-link"><i class="fas fa-list" style="font-size: large;"></i></a>
            </div>
          </div>
    </div>
  </div>

{% endblock %}

{% block parciales %}
{% endblock%}

Maquinaria/templates/listado_maquina.html
{% extends "base.html" %}

{% block container %}
<table class="table">   
    <tr>
        <thead class="thead-light">
            <tr>
                <th scope="col">Modelo</th>
                <th scope="col">Año</th>
                <th scope="col">Patente</th>
                <th scope="col">Estado</th>
                <th scope="col">Detalle</th>
                <th scope="col">Actualizar</th>
                <th scope="col">Dar de baja</th>
            </tr>
        </thead>
        <tbody>
            {% for maquina in maquinas %}
            <tr>
                    <td>{{maquina.modelo_verbose}}</td>
                    <td>{{maquina.agno}}</td>
                    <td>{{maquina.patente}}</td>
                    <td>{{maquina.estado_verbose}}</td>
                    <td>
                        <a href="{% url 'maquinaria:maquina-detail' maquina.id %}">
                            <i class="fas fa-info-circle" style="color: blue; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'maquinaria:maquina-update' maquina.id %}">
                            <i class="fas fa-pen-square" style="color: yellow; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'maquinaria:maquina-delete' maquina.id %}">
                            <i class="fas fa-ban" style="color: red; font-size: 1.5rem; text-align: center;"></i>
                        </a>
                    </td>

            </tr>
            {% endfor %}
        </tbody>
</table>

<a href="{% url 'maquinaria:maquina-create' %}">
    <button type="button" class="btn btn-success">
        <i class="fas fa-plus-square"> Agregar nueva maquina</i>
    </button>
</a>
{% if is_paginated %}
    {% include "_pagination.html" %}
{% endif %}

{% endblock %}

Maquinaria/templates/patente-consulta.html
{% extends "base.html" %}
{% block title %}
Crear usuario
{% endblock %}
{% block content_head %}
<!--Titulo-->
<div class="row round-borderform">
    <div class="col">
        <h2>Buscar maquina</h2>
        <!--Fin titulo-->
        {% endblock %}
        {% block container %}
        <!--Formulario-->
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">
                Buscar
            </button>
        </form>
        <!--Fin formulario-->
    </div>
</div>
{% endblock %}

Maquinaria/templates/update.html
{% extends "base.html" %}
{% block container %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Maquina Update #{{maquina.id}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Update</button>
        </form>
    </div>
</div>
{% endblock %}